title: The Gamma
email: tomas@tomasp.net
description: The Gamma project
baseurl: ""
url: ""
twitter_username: tomaspetricek
github_username:  tpetricek

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
